dotnet/netframeworkweb/Codes/Paladin/Paladin/Areas/Admin/Controllers/DataExportController.cs
using AutoMapper;
using Paladin.Controllers;
using Paladin.Infrastructure;
using Paladin.Models;
using Paladin.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace Paladin.Areas.Admin.Controllers
{
    public class DataExportController : PaladinController
    {
        private PaladinDbContext _context;

        public DataExportController(PaladinDbContext context)
        {
            _context = context;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetQuotesCSV()
        {
            var applicants = _context.Applicants.ToList();
            var mappedApplicants = new List<ApplicantVM>();
            foreach (var app in applicants)
            {
                mappedApplicants.Add(Mapper.Map<ApplicantVM>(app));
            }

            return CSV(mappedApplicants);
        }

        
    }
}

dotnet/netframeworkweb/Codes/Paladin/Paladin/Areas/Admin/Views/DataExport/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="col-md-3">
    <ul class="list-unstyled admin-menu">
        <li>
            @Html.ActionLink("Home", "Index", "Default")
        </li>
        <li>
            @Html.ActionLink("Data Export", "Index", "Default", null, new { area = "Admin" })
        </li>
        <li>
            @Html.ActionLink("Workflow", "Index", "Default")
        </li>
        <li>
            @Html.ActionLink("Activity", "Index", "Default")
        </li>
    </ul>
</div>

<div class="col-md-6">
    <h2 class="page-header">Export Data</h2>
    <p>Here you can export useful information from the database into CSV files.  Use them wisely!  If you have a request for an additional CSV, send us an email!</p>
    <hr />
    <h3>Applicant Quotes</h3>
    <p>Get a basic list of the people who have filled out the quote forms. <br /><br /> @Html.ActionLink("Download CSV", "GetQuotesCSV", "DataExport", new { area = "admin" }, new { @class = "btn btn-primary" })</p>
</div>